### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by carlosgj94** [DiegoLgr/Configfiles#1]
Hola! Si quieres buscar ejemplos de la gente de sus configs, este tipo de repos se llaman "dotfiles". Aquí tienes ejemplos: https://github.com/webpro/awesome-dotfiles
Y luego, he visto que usas Vim, bienvenido a la familia, si quieres ver mi config: https://github.com/carlosgj94/AppStormVim La instalacion es algo compleja hoy en día, pero uso los language servers de VSCode para ver la sintaxis y los errores y todo eso dentro de vim. Ademas de fuzzy search en proyectos y demas. Si quieres profundizar ahi me dices y te ayudo :D

**Comment by DiegoLgr** [comment]
Gracias! Le echare un ojo.
